/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stdio.h"
#include "stdlib.h"
#include "stdint.h"

typedef volatile unsigned int vuint32_t ;

//registers
#define GPIOA_BASE 0x40010800
#define GPIOA_ODR  *(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRH  *(vuint32_t *)(GPIOA_BASE + 0x04)

#define RCC_base 0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_base + 0x18)
#define RCC_CFGR *(vuint32_t *)(RCC_base + 0x04)
#define RCC_CR *(vuint32_t *)(RCC_base + 0x00)

int main(void)
{
	//enable pll source
	/*Bit 24 Set and cleared by software to enable PLL.
Cleared by hardware when entering Stop or Standby mode. This bit can not be reset if the
PLL clock is used as system clock or is selected to become the system clock. Software
must disable the USB OTG FS clock before clearing this bit.
0: PLL OFF
1: PLL ON */
	RCC_CR |= 1 << 24 ;
	// PLL multiplication >> *8
	/*Bits 21:18 PLLMUL[3:0]: PLL multiplication factor
These bits are written by software to define the PLL multiplication factor. They can be written only when PLL is disabled.
000x: Reserved
0010: PLL input clock x 4
0011: PLL input clock x 5
0100: PLL input clock x 6
0101: PLL input clock x 7
0110: PLL input clock x 8 <<
0111: PLL input clock x 9
10xx: Reserved
1100: Reserved
1101: PLL input clock x 6.5
111x: Reserved
Caution: The PLL output frequency must not exceed 72 MHz */
	RCC_CFGR |= (0b0110 << 18);
	// System clock Switch
	/*Bits 1:0 SW[1:0]: System clock Switch
Set and cleared by software to select SYSCLK source.
Set by hardware to force HSI selection when leaving Stop and Standby mode or in case of failure of
the HSE oscillator used directly or indirectly as system clock (if the Clock Security System is
enabled).
00: HSI selected as system clock
01: HSE selected as system clock
10: PLL selected as system clock <<
11: Not allowed */
	RCC_CFGR |= (0b10 << 0);
	//APB2 prescaler  /4
	/* Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	Set and cleared by software to control the division factor of the APB high-speed clock (PCLK2).
		0xx: HCLK not divided
	100: HCLK divided by 2
	101: HCLK divided by 4
	110: HCLK divided by 8
	111: HCLK divided by 16 */
	RCC_CFGR |= (0b101 << 11) ;
	//APB1 prescaler  /2
	/*Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
Set and cleared by software to control the division factor of the APB low-speed clock (PCLK1).
Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
0xx: HCLK not divided
100: HCLK divided by 2
101: HCLK divided by 4
110: HCLK divided by 8
111: HCLK divided by 16 */
	RCC_CFGR |= (0b100 << 8) ;
	/*Bit 2 IOPAEN: IO port A clock enable
	Set and cleared by software.
	0: IO port A clock disabled
	1: IO port A clock enabled*/
	//enable clock for GPIOA
	RCC_APB2ENR = 1<<2 ;
	//init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0X00200000;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for(int i=0;i<5000;i++); //simple delay
		GPIOA_ODR &= ~(1<<13);
		for(int i=0;i<5000;i++); //simple delay
	}

}
