/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stdio.h"
#include "stdlib.h"
#include "stdint.h"

typedef volatile unsigned int vuint32_t ;

//registers
#define GPIOA_BASE 0x40010800
#define GPIOA_ODR  *(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRH  *(vuint32_t *)(GPIOA_BASE + 0x04)

#define RCC_base 0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_base + 0x18)
#define RCC_CFGR *(vuint32_t *)(RCC_base + 0x04)

int main(void)
{
	//APB2 prescaler  /4
	/* Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	Set and cleared by software to control the division factor of the APB high-speed clock (PCLK2).
		0xx: HCLK not divided
	100: HCLK divided by 2
	101: HCLK divided by 4
	110: HCLK divided by 8
	111: HCLK divided by 16 */
	RCC_CFGR |= (0b101 << 11) ;
	//APB1 prescaler  /2
	/*Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
Set and cleared by software to control the division factor of the APB low-speed clock (PCLK1).
Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
0xx: HCLK not divided
100: HCLK divided by 2
101: HCLK divided by 4
110: HCLK divided by 8
111: HCLK divided by 16 */
	RCC_CFGR |= (0b100 << 8) ;
	/*Bit 2 IOPAEN: IO port A clock enable
	Set and cleared by software.
	0: IO port A clock disabled
	1: IO port A clock enabled*/
	//enable clock for GPIOA
	RCC_APB2ENR = 1<<2 ;
	//init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0X00200000;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for(int i=0;i<5000;i++); //simple delay
		GPIOA_ODR &= ~(1<<13);
		for(int i=0;i<5000;i++); //simple delay
	}

}
