/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Types.h"
//RCC
#define RCC_BASE   0x40021000
#define RCC_APB2ENR *((vuint32_t *)(RCC_BASE + 0x18))
//GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *((vuint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_ODR *((vuint32_t *)(GPIOA_BASE + 0x0C))
#define GPIOA_CRL *((vuint32_t *)(GPIOA_BASE + 0x00))

//EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR  *((vuint32_t *)(EXTI_BASE + 0x00))
#define EXTI_RTSR *((vuint32_t *)(EXTI_BASE + 0x08))
#define EXTI_PR   *((vuint32_t *)(EXTI_BASE + 0x14))

//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *((vuint32_t *)(AFIO_BASE + 0x08))


#define NVIC_ISER0 *((vuint32_t *)(0xE000E100))

void clock_init()
{
	RCC_APB2ENR |= 1<<2;
	//Bit 0 AFIOEN: Alternate function I/O clock enable
	RCC_APB2ENR |= 1<<0;
}
void GPIO_init()
{
	//pin 13 portA >> o/p
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;
	//Pin_A0 >> input floating
	GPIOA_CRL |= 1<<2;
}

int main(void)
{
	clock_init();
	GPIO_init();
	//EXTI0 configuration (x= 0) to port_A0
	AFIO_EXTICR1 = 0;
	//Enable EXTI line 0 ((mask >> 1))
	EXTI_IMR |= (1<<0) ;
	//Enable rising trigger
	EXTI_RTSR |= (1<<0) ;
	//Enable NVIC IRQ_6  >> EXTI0
	NVIC_ISER0 |= (1<<6);

}
void EXTI0_IRQHandler(void)
{
	//IRQ is happened EXTI0 port_A pin0 >> rising edge
	//toggle led pin A13
	GPIOA_ODR ^= (1<<13) ;

	//clear pending request for line 0
	EXTI_PR |= (1<<0) ;
}

