/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stdio.h"
#include "stdlib.h"
#include "stdint.h"

typedef volatile unsigned int vuint32_t ;

//registers
#define GPIOA_BASE 0x40010800
#define GPIOA_ODR  *(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRH  *(vuint32_t *)(GPIOA_BASE + 0x04)

#define RCC_base 0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_base + 0x18)

/*Bit 2 IOPAEN: IO port A clock enable
Set and cleared by software.
0: IO port A clock disabled
1: IO port A clock enabled*/

int main(void)
{
	//enable clock for GPIOA
	RCC_APB2ENR = 1<<2 ;
	//init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0X00200000;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for(int i=0;i<5000;i++); //simple delay
		GPIOA_ODR &= ~(1<<13);
		for(int i=0;i<5000;i++); //simple delay
	}

}
