/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Types.h"

#define set_bit(address, bit) address |= (1<<bit)
#define reset_bit(address, bit) address &= ~(1<<bit)
#define Toggle_bit(address, bit) address ^= (1<<bit)
#define read_bit(address, bit) ((address & (1 << bit)) >> bit)

//RCC
#define RCC_BASE   0x40021000
#define RCC_APB2ENR *((vuint32_t *)(RCC_BASE + 0x18))
//GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *((vuint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_CRL *((vuint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_ODR *((vuint32_t *)(GPIOA_BASE + 0x0C))
#define GPIOA_IDR *((vuint32_t *)(GPIOA_BASE + 0x08))


#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *((vuint32_t *)(GPIOB_BASE + 0x04))
#define GPIOB_CRL *((vuint32_t *)(GPIOB_BASE + 0x00))
#define GPIOB_ODR *((vuint32_t *)(GPIOB_BASE + 0x0C))
#define GPIOB_IDR *((vuint32_t *)(GPIOB_BASE + 0x08))


void clock_init()
{
	//PORTA
	RCC_APB2ENR |= 1<<2;
	//PORTB
	RCC_APB2ENR |= 1<<3;

}
void GPIO_init()
{
	// PA1 I/P HIGH Z
	GPIOA_CRL &= ~(0b1111 << 4) ;
	GPIOA_CRL |= (0b0100 << 4) ;
	//PB1 O/P PUSH - PULL
	GPIOB_CRL &= ~(0b1111 << 4) ;
	GPIOB_CRL |= (0b0001 << 4) ;
	//PA13 I/P HIGH Z
	GPIOA_CRH &= ~(0b1111 << 20) ;
	GPIOA_CRH |= (0b0100 << 20) ;
	//PB13 O/P PUSH - PULL
	GPIOB_CRH &= ~(0b1111 << 20) ;
	GPIOB_CRH |= (0b0001 << 20) ;

}

void mywait(int n)
{
	for(int i =0 ; i<255;i++);
}
int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		//PA1 >> PUR normally 1
		if( read_bit(GPIOA_IDR,1) == 0) //single pressing
		{
			GPIOB_ODR ^= 1<<1 ;
			while(  read_bit(GPIOA_IDR,1) == 0);
		}
		//PA13 PDR normally 0
		if(read_bit(GPIOA_IDR,13) == 1) //multi pressing
		{
			GPIOB_ODR ^= 1<<13 ;

		}
		mywait(1);
	}
}


